import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { AuthProvider } from "@/context/AuthContext";
import Notification from "@/components/common/Notification";
import { TicketsProvider } from "@/context/TicketsContext";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<AuthProvider>
					<TicketsProvider>
						<Header />
						<main>{children}</main>
						<Footer />
						<Notification />
					</TicketsProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
